# CISCO SWITCHES CONNECTION
ansible_user: admin
ansible_password: Admin1234.
ansible_connection: network_cli
ansible_network_os: cisco.ios.ios

# Ansible Machien Management IP
local_ipv4: 10.99.0.100
