- name: Base configuration
  hosts: l2switches:l3switches
  gather_facts: no
  roles:
    - base

- name: Coniguring Vlans and SVIs
  hosts: l2switches:l3switches
  gather_facts: no
  roles:
    - vlan

- name: Setting Ip Routing and Acls
  hosts: l3switches
  gather_facts: no
  roles:
    - acl

- name: Distibution Switch Configuration
  hosts: l3switches
  gather_facts: no
  roles:
    - dist_switch
