# Switch Variables
ansible_host: 10.0.99.5

# Interfaces
unused_ports: "gi1/2-3,gi2/0-3,gi3/0-2"
management_port: "gi3/3"

# Vlans
vlans:
  - {id: 10, name: Servers}
  - {id: 20, name: Corporate}
  - {id: 30, name: Clients}
  - {id: 99, name: Management}

# SVIs (y VRRP con vrrp_prio + vrrp_ip + vrrp_id)
svis:
  - {name: "vlan 99", address: "10.0.99.5", mask: "24"}
  - {name: "vlan 10", address: "10.0.10.253", mask: "24", vrrp_prio: "100", vrrp_ip: "10.0.10.254", vrrp_id: "10"}
  - {name: "vlan 20", address: "10.0.20.253", mask: "24", vrrp_prio: "100", vrrp_ip: "10.0.20.254", vrrp_id: "20"}
  - {name: "vlan 30", address: "10.0.30.253", mask: "24", vrrp_prio: "100", vrrp_ip: "10.0.30.254", vrrp_id: "30"}

# ACLs
acl_list:
  acls:
    - name: "FROM-20"
      acl_type: extended
      aces:
        - {sequence: 5, grant: permit, protocol: ip, source: {address: "10.0.20.0", wildcard_bits: "0.0.0.255"}, destination: {address: "10.0.10.0", wildcard_bits: "0.0.0.255"}}
        - {sequence: 15, grant: permit, protocol: ip, source: {any: true}, destination: {any: true}}
    - name: "FROM-10"
      acl_type: extended
      aces:
        - {sequence: 10, grant: permit, protocol: ip, source: {any: true}, destination: {any: true}}
    - name: "FROM-30"
      acl_type: extended
      aces:
        - {sequence: 5, grant: deny, protocol: ip, source: {address: "10.0.30.0", wildcard_bits: "0.0.0.255"}, destination: {address: "10.0.0.0", wildcard_bits: "0.0.255.255"}}
        - {sequence: 10, grant: permit, protocol: ip, source: {any: true}, destination: {any: true}}
    - name: "FROM-99"
      acl_type: extended
      aces:
        - {sequence: 20, grant: permit, protocol: ip, source: {any: true}, destination: {any: true}}

  dest_vlan:
    - name: "vlan 10"
      access_groups: [{acls: [{name: "FROM-10", direction: "in"}], afi: "ipv4"}]
    - name: "vlan 20"
      access_groups: [{acls: [{name: "FROM-20", direction: "in"}], afi: "ipv4"}]
    - name: "vlan 30"
      access_groups: [{acls: [{name: "FROM-30", direction: "in"}], afi: "ipv4"}]
    - name: "vlan 99"
      access_groups: [{acls: [{name: "FROM-99", direction: "in"}], afi: "ipv4"}]


## falta puertos hacia el router, portsecurity y (lacp????)....

# Access ports
access_ports:
  - {interface: "g3/3",  mode: access, vlan: 99}

# Trunk ports (Añadir portchannel si necesario)
trunk_ports:
  - {interface: "gi0/0",  mode: trunk, native_vlan: 999, allowed_vlans: "10,20,99", encapsulation: "dot1q"}
  - {interface: "gi0/2",  mode: trunk, native_vlan: 999, allowed_vlans: "10,20,99", encapsulation: "dot1q"}
  - {interface: "gi0/3",  mode: trunk, native_vlan: 999, allowed_vlans: "30,99", encapsulation: "dot1q"}
  - {interface: "{{ port_channels[0].name }}", mode: trunk, native_vlan: 999, allowed_vlans: "10,20,30,99", encapsulation: "dot1q"}

# PortChannel
port_channels:
  - name: "Port-channel 1"
    members:
      - {member: "g1/0", mode: "active"}
      - {member: "g1/1", mode: "active"}

# Router link
uplink: {interface: "g0/1", ip: "10.0.0.3", mask: "24"}

# OSPF (añade a networks las redes a compartir con ospf, pej: vlans...)
ospf:
  - id: "1"
    networks:
      - {address: "10.0.0.0", wildcard_bits: "0.0.0.255", area: "1"}
